spring:
  application:
    name: Personal Information Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_information_manager
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null
jwt.secret: ${JWT_SECRET_KEY}